import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';

import "./globals.css";
import BootstrapClient from "./components/bootstrapClient";
import Navbar from "./components/Navbar";
import { AntdRegistry } from '@ant-design/nextjs-registry';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DeepDesignWeb | eSchool",
  description: "Generated by Deep Design Web",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body classNameName={inter.className}>
        <Navbar />
      

        <AntdRegistry>{children}</AntdRegistry>
      <BootstrapClient />
      </body>
    </html>
  );
}
